site:
  title: Spring CLI
  url: https://docs.spring.io/spring-cli/reference
  start_page: spring-cli::index.adoc
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: ../
      start_path: docs
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: static
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.7/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll

