name: Dev Native

on:
  workflow_dispatch:

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: win
            os: win22-8-32
            graal: dev
    name: CI Native ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal }}
          java-version: 21
          set-java-home: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew build nativeCompile
      - uses: actions/upload-artifact@v2
        with:
          name: spring-up-${{ matrix.nickname }}
          path: build/native/nativeCompile/
          retention-days: 1
