name: e2e

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 1,3,5'

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: macos
            os: macos-latest
            graal: dev
          - nickname: linux
            os: ubuntu-latest
            graal: dev
          - nickname: windows
            os: win22-8-32
            graal: dev
    name: E2E ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal }}
          java-version: 21
          set-java-home: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          ./gradlew clean build nativeBuild -x test
      - name: run e2e tests
        working-directory: e2e/spring-cli-e2e-tests
        run: |
          npm install
          npm run build-spring-shell-e2e
          npm test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: e2e/spring-cli-e2e-tests/junit.xml
